solr:
  build: ./baseubuntu
  hostname: solr
  volumes:
    - ./master/puppet/modules/solr_asia/volumes/data:/opt/solr/data
  external_links:
    - puppetmaster:master

mysql:
  build: ./basecentos
  hostname: mysql
  ports:
    - "3306:3306"
  external_links:
    - puppetmaster:master

apache:
  build: ./basecentos
  hostname: apache
  volumes:
    - ./master/puppet/modules/apache_asia/volumes/web:/var/www
  ports:
    - "8080:80"
    - "8888:88"
    - "2121:21"
    - "2222:22"
  external_links:
    - puppetmaster:master
  links:
    - solr
    - mysql
