<?php
/**
 * Guia de Barcelona - Agenda and Directory
 *
 * This file is part of Guia Barcelona v1.0.0
 * @author Elazos Software Factory
 **/

define("_DATEFORMAT","d/m/Y");
define("_FINPAG","Copyright © ".date("Y")." <a href=\"http://www.bcn.cat\">Barcelona City Council</a> - All Rights Reserved.");
define("_SITENAME","Barcelona Guide");
define("_SITEOWNER","Barcelona City Council");
define("_SLOGAN","Barcelona Guide");
define("_SITEDESC","City of Barcelona's events and activities calendar and organisations and facilities directories");
define("_KEYWORDS","agenda, calendar, ceremonies, ceremony, activities, directory, amenity, amenities, entities, entity, restaurants, associations");
define("_CHARSET","UTF-8");
define("_IDIOMA","en");
define("_LANGUAGE",3);
define("_HOME","Bcn Guide");
define("_PIEPAGINA","Footer");
define("_FIND","Search");
define("_FOUND","Found");
define("_ROWS","results");
define("_PAGS","Pages");   
define("_OF","of");
define("_NEXT","Next");
define("_PREVIOUS","Previous");

define("_NAME","Name");
define("_TICKET","Ticket");

define("_DISTRICT","District");
define("_DISTRICTSTR","District");
define("_BARRI","Area");
define("_BARRISTR","Area");
define("_STREET","Address");
define("_STREETNUM_I","Num");
define("_TYPE","Type");
define("_SECTIONNAME","Section");
define("_ADDRESS","Address");
define("_POSTALCODE","Post Code");
define("_CITY","City");

define("_VOLIEUDIR","Did you mean:");
define("_SIGLA","Abbreviation");
define("_INSTITUTIONNAME","Where:");
define("_RSS","RSS");
define("_ALPHA","Alphabetically");
define("_POPULARITY","popularity");
define("_LATEST","Latest");
define("_SORTBY","Sorted by:");

define("_SEARCH","Search results");

define("_DETALL","Details");

define("_NOT_FOUND","No results found for your search");
define("_NOTFOUND","Page not found");

define("_AG","Agenda");
define("_EQ","Entities and amenities");

define("_00060001","Tiquet 60001");
define("_00060002","Free");
define("_00060003","Payment");	
define("_00060004","Reserved");	
define("_00060005","Groups only");	
define("_00060006","By Invitation");	

// INTERESTINFO
define("_00100000","Information of interest - Facilities");
define("_00100002","Email");
define("_00100003","Web");
define("_00100004","Accessibility website");
define("_00100005","Facebook");
define("_00100006","Twitter");
define("_00100007","YouTube");

define("_00030001","Phone");
define("_00030002","Email");
define("_00030003","Website");
define("_00030004","Registration Phone");
define("_00030005","Event registration fax");
define("_00030006","Ticket sales fax");
define("_00030007","Ticket sales telephone");
define("_00030008","Tickets sales Email");	
define("_00030009","Registration email");
define("_00030010","Reservations email");
define("_00030011","Reservations telephone");
define("_00030012","Registration website");
define("_00030013","Season ticket telephone");
define("_00030014","Ticket sales website");
define("_00030015","Video");
define("_00030016","Information telephone");
define("_00030017","Facebook");
define("_00030018","Twitter");
define("_00030019","YouTube");


//PHONE_CODES
define("_00020001","Phone");	
define("_00020027","Fax");	
define("_00020003","Phone");	
define("_00020006","Information");	

define("_INTERNETREF","Picture");	

define("_APROPDAQUI","Nearby");	
define("_COMANAR","How to go");	

define("_GMAPX","Latitude");	
define("_GMAPY","Longitude");

define("_SHOWMAP","See map");
define("_MAPLABELSEARCH","Geolocation results");

define("_MVOTEDMONTH","EVENTS+RATED");
define("_MVIEWEDMONTH","THE+VIEWED");

define("_CATS_AGENDA","AGENDA CATEGORIES");
define("_CATS_DIRECTORI","DIRECTORY CATEGORIES");

define("_VEURE_CATS_AGENDA","See all Agenda Events");
define("_VEURE_CATS_DIRECTORI","See all the directories");


define("_CATS_H_AGENDA","Activities calendar");
define("_CATS_H_DIRECTORI","Entities and amenities directory");

define("_HORARIS","Time tables");
define("_PREUS","Prices");
define("_PERIOD","Period");
define("_DAYS", "Days");
define("_HOURS", "Hours");
define("_PRICE", "Prices");
define("_REMARKS","Comments"); 
define("_PERMANENT","Ongoing event"); 
define("_RECOMMENDED","USERS WHO VIEWED THIS, ALSO VIEWED...");

define("_CLASSALL","Classification"); 
define("_CLASSLABEL","You can find this file in"); 
define("_SECTION","Sections from this amenity"); 
define("_RELATIONS","Others"); 
define("_MORE","More"); 
define("_NO_AV_LG","No available content in this language");
define("_LIKEIT","I like");


define("_P","Price");
define("_NOPREU","Not reported");
define("_DE1A30","From 1 € to 30 €");
define("_DE30A60","From 30 € to 60 €");
define("_MES60","More than 60 €");

define("_D","When");
define("_AVUI","Today");
define("_DEMA","Tomorrow");
define("_CAP","This Weekend");
define("_CAPS","Weekends");
define("_SETMANA","Next 7 days");
define("_MES","Next 30 days");

define("_DATE","When:");//Fecha
define("_ENDDATE","to");//Del 21/1/2011 al 31/1/2011
define("_BEGINDATE","From"); //Del 21/1/2011 al 31/1/2011
define("_PHONENUMBER","Phone:");
define("_ID","");
define("_POS","");
define("_EQUIPMENT_ID","Equipment_id");

define("_AGEQ","Events are held");
define("_NODISPONIBLE","Not available");


define("_DROPFILTER","Remove filter");
define("_YOURFILTERS","Your filters");
define("_FILTERS","Filters");
define("_NUMROWS","results per page");
define("_DISPLAYING","Displaying");
define("_TO","to");
define("_RESULTS","results of ");
define("_ACTEPERMANENT","Ongoing event");

define("_ACTDESTACADES","FEATURED EVENTS");
define("_RECOM_ID","id");
define("_IMATGECOS","Picture"); 
define("_IMATGE","Picture"); 
define("_TITOL","Title"); 
define("_RESUM","Summary"); 
define("_URLVIDEO","Video"); 
define("_ENTITY_ID","entity_id");
define("_TEXTE","");
define("_NOEXIST","");
define("_TP","");

define("_RELATED","Related items");
define("_APARCS","Car Parks");
define("_RESTAURANTS","Restaurants");
define("_TEMA_TOTS","All");
define("_STATUS_ID","Status");
define("_AG_STATUS_ID_1","Event Postponed");
define("_AG_STATUS_ID_2","Event Suspended");

define("_ENTITY_TYPE","");
define("_COORDADDRESSX","");
define("_COORDADDRESSY","");
define("_STAIR",""); 
define("_FLOOR",""); 
define("_DOOR",""); 
define("_TEMA",""); 
define("_ID_TEMA","");

define("_COMMENTS","");
define("_ACTNAME","");
define("_TICKETTYPE_CODE","");
define("_ACTTYPE","");
define("_WARNING","");
define("_INSTITUTION_ID","");
define("_VOTES","");
define("_NAMEASIA","");
define("_TITULARITAT","Titularidad");
define("_0010201001","Públicos");
define("_0010201002","Privados");
define("_0013201002","Concertados o subvencionados");

define("_N0010201001","Centro público");
define("_N0010201002","Centro privado");
define("_N0013201002","Centro concertado o subvencionado");
define("_CODE_TIT","Titularidad");
define("_CODE_INFO","Servicios");

define("_002200400","Comedor");
define("_002200410","Cocina propia");
define("_002200412","Acogida fuera del horario escolar");
define("_002200441","Actividades extraescolares/casales");

define("_HOMEBCNTITOL","Diary");
define("_HOMEBCNTOTS","All events in bcn.cat");

define("_ACCESSIBILITY","Accessibility");
define("_0010501000","Amb servei de bany per a persones amb cadira de rodes");
define("_0010501001","Accessibility for people with disabilities");
define("_0010501002","No accessible per a persones amb disminució física");
define("_0010501003","Practicable per a persones amb disminució física (parcialment adaptat)");
define("_0010501004","Amb WC adaptat per a persones amb disminució");
define("_0010501005","Sense WC adaptat per a persones amb disminució");
define("_0010501006","Adaptat per a esportistes amb disminució");
define("_0010501007","No adaptat per a esportistes amb disminució");
define("_0010501008","Amb espai per a cadires de rodes");
define("_0010501009","Sense espai per a cadires de rodes");
define("_0010501010","Amb aparcament reservat per a persones amb disminució");
define("_0010501011","Sense aparcament reservat per a persones amb disminució");
define("_0010501012","Amb caseta vestidor adaptada per a persones amb disminució");
define("_0010501013","Amb dutxes adaptades per a persones amb disminució");
define("_0010501014","Sense dutxes adaptades per a persones amb disminució");
define("_0010501015","Parcialment adaptat per a esportistes amb disminució");
define("_0010501016","Amb vehicles adaptats per a persones amb disminució");
define("_0010501017","Adaptació de vehicles per a persones amb disminució física");
define("_0010501018","Amb visita comentada per a persones amb disminució auditiva");
define("_0010501019","Parcialment accessible per a persones amb disminució física");

define("_CODE_URL","Web Site");
define("_STATUS","Status");
define("_ATENCIO_EQ","Notice");
define("_CODE_COMARCA","Comarca");

?>