<?php
// $Id: asia_gmapmarker_guia.module, v1.2 2014/10/16

/******************************/
/* Includes necessaris        */
/******************************/

include 'functions-asia_gmapmarker.php';


/**
 * Implementation of hook_init().
 */



function asia_gmapmarker_guia_init() {

	global $language;
	$idma = $language->language; 
    $base_url=$GLOBALS['base_url'];
	$detall = $base_url.'/'.$idma.'/detall/';
    $ico_markers=$base_url.'/'.drupal_get_path('module', 'asia_gmapmarker_guia').'/markers/';   
	$gmcanal =  variable_get('gmcanal','');  
	$activeList = variable_get('gmactivelist', '');
	//$literals = array(t('View map'),t("View list"), t('When'), t('Where'), t('From'), t('to') );
	$literals = array(t('View map'),t("View list"), t('When'));	
	
	//config del mapa 
	$zoom = variable_get('gmzoom', '');
	$lat = variable_get('gmlatlngx','');
	$lng = variable_get('gmlatlngy','');	
	  
  
  	
	
	// si la llista esta activada
	if($activeList[1]==1){
		$activeList = 1;
	}else{
		$activeList = 0;
	}	
	$nr = variable_get('gmnr', '');	
		
	
	$urlJson = "http://guia.bcn.cat/index.php?pg=search&xout=json";

	if($gmcanal != "" && $gmcanal != "<none>" ){
		$canal = $gmcanal;
	}elseif($gmcanal == "<none>"){
		$canal = '';  
	}else{
		$canal = variable_get('asia_canal','');  
	}
	
	if($canal !=""){
		$urlJson = $urlJson."&canal=".$canal;
	}

	if($nr != ""){
		$urlJson = $urlJson."&nr=".$nr;
	}

	$urlJson = $urlJson."&idma=".$idma;
	
	drupal_add_js('http://cdnjs.cloudflare.com/ajax/libs/jquery-ajaxtransport-xdomainrequest/1.0.1/jquery.xdomainrequest.min.js','external');
 
	drupal_add_js(drupal_get_path('module', 'asia_gmapmarker_guia') .'/js/asia_gmapmarker.js');	
    drupal_add_js(array('base_url' => $base_url, 'detall' => $detall, 'urljson' => $urlJson, 'ico_markers' => $ico_markers,'activelist' => $activeList, 'literals' => $literals), 'setting'); 
	
	drupal_add_js("var mapGM; function initializeGM() { var mapOptionsGM = { zoom: " . $zoom . ", center: new google.maps.LatLng(" . $lat . ", " . $lng . ")}; mapGM = new google.maps.Map(document.getElementById('map-canvasGM'), mapOptionsGM);} google.maps.event.addDomListener(window, 'load', initializeGM);",'inline');
	
	drupal_add_css(drupal_get_path('module', 'asia_gmapmarker_guia') .'/css/asia_gmapmarker.css');	
  

 // Setup IE meta tag to force IE rendering mode
  $meta_ie_render_engine = array(  	
  	'#type' => 'html_tag', 
    '#tag' => 'meta',
    '#attributes' => array(
      'http-equiv' => 'X-UA-Compatible',
      'content' =>  'requiresActiveX=true',
    ),
    '#weight' => '-99999',
	
  );
 
  // Add header meta tag for IE to head
  drupal_add_html_head($meta_ie_render_engine, 'meta_ie_render_engine');
  
}


/**
 * Implementation of hook_theme().
 */

function asia_gmapmarker_guia_theme($existing, $type, $theme, $path ) {
	return array(
 
 		'gmapmarker' => array(
			'variables' => array(),
			'template' => 'templates/gmapmarker',
			'path' => drupal_get_path('module', 'asia_gmapmarker_guia'),
		),		
		
				
	);
}


/**
 * Implementation of hook_block().
 */

function asia_gmapmarker_guia_block_info() {
	$blocks[0] = array(
      'info' => t('ASIA GMAPS MARKER: Gmaps marker'), 
      'weight' => 0, 
      'status' => 1, 
      'region' => 'Disabled',
    );

	
	return $blocks;
}

 function asia_gmapmarker_guia_block_view($delta = ''){ 
 
	//Recull idioma
		global $language;
		$lang = $language->language; 
		
		
 	
	// Si esta activada la recollida de variable 
	// Inicia i recull la variable districte si ve
	
	$subject = t('GMAPS MARKER');		
 	
 	switch ($delta) {
      case 0:	  
     	$block = array(
          'subject' => $subject,          
          'content' => mostra_gmapmarker(),
        );
		break;
    }
    return $block;
}


			
					





function asia_gmapmarker_guia_block_configure($delta = ''){ 

    switch ($delta) {		
		case 0:		
			$form['config_map']= array(
				'#type' => 'fieldset',
				'#title' => t('Setting the map'),
				// Set up the wrapper so that AJAX will be able to replace the fieldset.	
			);
			$form['config_map']['gmzoom'] = array(
			  '#type' => 'textfield', 
			  '#title' => t('Zoom'), 
			  '#default_value' => variable_get('gmzoom', ''),
			  '#element_validate' => array('gmapsmarker_gmzoom_validate'),
			);
			$form['config_map']['gmlatlngx'] = array(
			  '#type' => 'textfield', 
			  '#title' => t('Latitude'), 
			  '#default_value' => variable_get('gmlatlngx', ''),
			  '#element_validate' => array('gmapsmarker_gmlatlngx_validate'),
			);
			
			$form['config_map']['gmlatlngy'] = array(
			  '#type' => 'textfield', 
			  '#title' => t('Length'), 
			  '#default_value' => variable_get('gmlatlngy', ''),
			  '#element_validate' => array('gmapsmarker_gmlatlngy_validate'),
			);
			
			$form['gmcanal'] = array(
			  '#type' => 'textfield', 
			  '#title' => t('Channel'), 
			  '#default_value' => variable_get('gmcanal', ''),
			  '#description' => t('Specify the channel, if this is different from the configuration of the module asia. Put &lt;none&gt; if you want some.'),
			);
				
			
			$form['gmnr'] = array(
			  '#type' => 'textfield', 
			  '#title' => t('Number of results to be shown'), 
			  '#default_value' => variable_get('gmnr', 100),
			  '#description' => t('This map has no pagination. In show number of points should be raised.'),
			  '#element_validate' => array('gmapsmarker_gmnr_validate'),
			);					
		
			$form['gmtipus'] = array(
				'#type' => 'checkboxes',
				'#title' => t('Type list '), 
				'#default_value' => variable_get('gmtipus', array(1 => 0,)),
				'#options' => array ( 				
					1 => t('Show events'),		
					2 => t('Show directories'),		
				),
				'#description' => t('To show that the results should be a list type selected'),
				'#element_validate' => array('gmapsmarker_gmtipus_validate'),
			);	
			
			$form['gmactivelist'] = array(
				'#type' => 'checkboxes',
				'#title' => t('List '), 
				'#default_value' => variable_get('gmactivelist', array(1 => 0)),
				'#options' => array ( 
					1 => t('Active list'),
					2 => t('Active option all'),			
				),
				
			);				
			
			/***/
			


      $form['list_fieldset']= array(
		'#type' => 'fieldset',
		'#title' => t('Criteris de cerca'),
		// Set up the wrapper so that AJAX will be able to replace the fieldset.
		'#collapsible' => TRUE,
		'#collapsed' => TRUE,
	 
		'#prefix' => '<div class="list-item">',
		'#suffix' => '</div>',
		
	  );

	
	
	// carga de guardats
	$items = variable_get('listcriteris');
	
	
	 for ($i = 0; $i < 30; $i++) {
		 
		 $form['list_fieldset']['item_fieldset'][$i]= array(
			'#type' => 'fieldset',
			'#title' => t('Item'). '-' . $i,
			// Set up the wrapper so that AJAX will be able to replace the fieldset.
			'#collapsible' => TRUE,
			'#collapsed' => TRUE,
		 
			'#prefix' => '<div class="item">',
			'#suffix' => '</div>',
			
		  );		
		//si existeix text
		if (isset($items[$i][0])){
			$form['list_fieldset']['item_fieldset'][$i]['text-'.$i] = array(
			  '#type' => 'textfield',
			  '#title' => t('Text'),
			  '#default_value' => $items[$i][0],
		
			);
			
		}else{
			$form['list_fieldset']['item_fieldset'][$i]['text-'.$i] = array(
		  		'#type' => 'textfield',
		  		'#title' => t('Text'),	
			);
		}
		//si existeix url
		if (isset($items[$i][1])){
			$form['list_fieldset']['item_fieldset'][$i]['url-'.$i] = array(
			  '#type' => 'textfield',
			  '#title' => t('Url'),
			  '#default_value' => $items[$i][1],
			  '#description' => '<p style="font-style: italic; font-size:0.9em;">' . t('Example:') . '<strong style="color:#000; font-weight: bold; font-size:1em;">&code0=0040101008</strong></p><p style="font-style: italic; font-size:0.9em;">http://guia.bcn.cat/index.php?pg=search&q=*:*<strong style="color:#000; font-weight: bold; font-size:1em;">&code0=0040101008</strong></p>',
			);
		}else{
			$form['list_fieldset']['item_fieldset'][$i]['url-'.$i] = array(
		 		'#type' => 'textfield',
		  		'#title' => t('Url'),
				'#description' => '<p style="font-style: italic; font-size:0.9em;">' . t('Example:') . '<strong style="color:#000; font-weight: bold; font-size:1em;">&code0=0040101008</strong></p><p style="font-style: italic; font-size:0.9em;">Url guia: http://guia.bcn.cat/index.php?pg=search&q=*:*<strong style="color:#000; font-weight: bold; font-size:1em;">&code0=0040101008</strong></p>',
		 	);
		}
		
	  }					
	break;		
		
	}
	return $form;
}





function asia_gmapmarker_guia_block_save($delta = '', $edit = array()) { 

    switch ($delta) {
		case 0:		
		variable_set('gmcanal', $edit['gmcanal']);
		variable_set('gmactivelist', $edit['gmactivelist']);
		variable_set('gmzoom',$edit['gmzoom']);
		variable_set('gmlatlngx',$edit['gmlatlngx']);
		variable_set('gmlatlngy',$edit['gmlatlngy']);		
		
		$items = array();
		for ($i = 0; $i < 30; $i++) {
			if(!empty($edit['text-' . $i]) || !empty($edit['url-' . $i])){
				$items[$i] = array($edit['text-' . $i], $edit['url-' . $i]);
			}
		}				
		variable_set('listcriteris', $items);
		variable_set('gmnr', $edit['gmnr']);	
		variable_set('gmtipus', $edit['gmtipus']);	
			
		break;
	}
}

function gmapsmarker_gmlatlngx_validate($element){
	if(!is_numeric($element['#value'])){
		form_set_error('', t('Incorrect latitude.'));
	}
}
function gmapsmarker_gmlatlngy_validate($element){
	if(!is_numeric($element['#value'])){
		form_set_error('', t('Incorrect lenght.'));
	}
}


function gmapsmarker_gmzoom_validate($element){
	if(!is_numeric($element['#value'])){
		form_set_error('', t('Incorrect zoom.'));
	}
}

function gmapsmarker_gmnr_validate($element){
	if(!is_numeric($element['#value'])){
		form_set_error('', t('Incorrect number of results.'));
	}
}

function gmapsmarker_gmtipus_validate($element){
	if( empty($element['#value']) ){
		form_set_error('', t('You have to choose a type of list'));
	}
}