<?php
/**
 * Guia de Barcelona - Agenda and Directory
 *
 * This file is part of Guia Barcelona v1.0.0
 * @author Elazos Software Factory
 **/
//ini_set('display_errors',1);
//error_reporting(E_ALL);

date_default_timezone_set("Europe/Paris");
define("_DB_NAME","guiabcn");
define("_DB_USER","imisql");
define("_DB_PWD","TF3461fy1");
define("_DB_HOST","10.254.162.14");
define("_TABLE_PREFIX","");
define('SOLR_SERVER_HOSTNAME', '10.254.162.15');

?>