<?php
/**
 * Guia de Barcelona - Agenda and Directory
 *
 * This file is part of Guia Barcelona v1.0.0
 * @author Elazos Software Factory
 **/

/**
 *Returns xml node for home page.
 *Gets content from a xml file defined in xml navigator file.
 *@package blocks_public
 **/
/*
require_once("includes/forms/forms_xml.php");

$form = new xmlform("f1","","GET",""._FIND."");
$form->add_textbox("search","",80,80);
$form->add_hidden("data");
if (!$form->process()){
	$form->fields["data"]->value="pg=search"; 
}
$this->html_out .="<sbox>".$form->draw()."</sbox>";
*/
?>