<?php
// $Id: agenda.recomenada, v1.0 2014/06/01

/******************************/
/* Includes necessaris        */
/******************************/

include 'functions-agenda_recomenada.php';


function agenda_recomenada_init() {
	
	drupal_add_js(drupal_get_path('module', 'agenda_recomenada') .'/js/agrecom.js');
  
}


/**
 * Implementation of hook_menu().
 */

function agenda_recomenada_menu() {
 	
   
	$items = array();
	
	$items['agenda-recomenada/%'] = array(
      'page callback' => 'mostra_agenda_recomenada_page',
	  'title' => '',
  	  'access arguments' => array('access content'),
	  'page arguments' => array(1),
    );
	
	$items['especials/%'] = array(
      'page callback' => 'mostra_agenda_recomenada_especials',
	  'title' => '',
  	  'access arguments' => array('access content'),
	  'page arguments' => array(1),
    );

	return $items;

}

/**
 * Implementation of hook_theme().
 */

function agenda_recomenada_theme($existing, $type, $theme, $path ) {
	return array(
 
 		
		'agenda_recomenada' => array(
			'variables' => array('arrXml' => NULL),
			'template' => 'templates/agenda_recomenada',
			'path' => drupal_get_path('module', 'agenda_recomenada'),
		)		
				
	);
}


/**
 * Implementation of hook_block().
 */

function agenda_recomenada_block_info() {
	
	$blocks[0] = array(
      'info' => t('Agenda Recomenada: Block Generic'), 
      'weight' => 0, 
      'status' => 1, 
      'region' => 'Disabled',
    );
	return $blocks;
}

 function agenda_recomenada_block_view($delta = ''){ 
 
 	switch ($delta) {
    
	  case 0:
     	$block = array(
          'subject' => "Destacats dels propers dies",          
          'content' => mostra_agenda_recomenada("generic"),
       );
	   break;		
    }
    return $block;
}