<?php
/**
 * Guia de Barcelona - Agenda and Directory
 *
 * This file is part of Guia Barcelona v1.0.0
 * @author Elazos Software Factory
 **/

/**
* Links to public page
* 
*@package Init_Public
**/
/**
*Main page with parameters
**/
define("LK_PAG","index.php?");
/**
*Logout page
**/
define("LK_LOGOUT","logout.php");
/**
*Admin Page
**/
define("LK_HOME_ADM","index.php");
/**
*Home page
**/
define("LK_HOME","index.php");



?>