<?php
/**
 * Guia de Barcelona - Agenda and Directory
 *
 * This file is part of Guia Barcelona v1.0.0
 * @author Elazos Software Factory
 **/


define("_DATEFORMAT","d/m/Y");
define("_FINPAG","Copyright © ".date("Y")." <a href=\"http://www.bcn.cat\">Ayuntamiento de Barcelona</a> - All Rights Reserved.");
define("_SITENAME","Guía de escuelas 2013 - 2014");
define("_SITEOWNER","Ayuntamiento de Barcelona");
define("_SLOGAN","Guía Barcelona");
define("_SITEDESC","Guía de escuelas 2013 - 2014"); 
define("_KEYWORDS","Guía de escuelas 2013 - 2014, agenda, calendario, actos, acto, actividades, directorio, directorios, equipamiento, equipamientos, entidades, entidad, restaurantes, asociaciones");
define("_CHARSET","UTF-8");
define("_IDIOMA","es");
define("_LANGUAGE",2);
define("_HOME","Guía de escuelas 2013 - 2014");
define("_PIEPAGINA","Pie página");
define("_FIND","Buscar");
define("_FOUND","Encontrados");
define("_ROWS","registros");
define("_PAGS","Páginas");   
define("_OF","de");
define("_NEXT","Siguiente");
define("_PREVIOUS","Anterior");

define("_NAME","Nombre");
define("_TICKET","Entrada");

define("_DISTRICT","Distrito");
define("_DISTRICTSTR","Distrito");
define("_BARRI","Zona");
define("_BARRISTR","Zona");
define("_STREET","Dirección");
define("_STREETNUM_I","Núm.");
define("_TYPE","Tipo");
define("_SECTIONNAME","Sección");
define("_ADDRESS","Dirección");
define("_POSTALCODE","Código postal");
define("_CITY","Población");

define("_VOLIEUDIR","Quieres decir:");
define("_SIGLA","Sigla");
define("_INSTITUTIONNAME","Dónde");
define("_RSS","RSS");
define("_ALPHA","Alfabéticamente");
define("_POPULARITY","Popularidad");
define("_LATEST","Más recientes");
define("_SORTBY","Ordenar por:");

define("_SEARCH","Búsqueda");
define("_DETALL","Detalle");
define("_NOT_FOUND","No se han encontrado resultados para la búsqueda");
define("_NOTFOUND","No se ha encontrado.");
define("_AG","Agenda");
define("_EQ","Oferta educativa");

define("_00060001","Tiquet 60001");
define("_00060002","Gratuita");
define("_00060003","De pago");	
define("_00060004","Reservada");	
define("_00060005","Solo grupos");	
define("_00060006","Con Invitación");	

// INTERESTINFO
define("_00100002","Email");
define("_00100003","Correo electrónico");
define("_00030003","Correo electrónico");
define("_00030001","Teléfono");
define("_00030002","Correo electrónico");
define("_00030004","Teléfono de inscripción");
define("_00030011","_00030011");
define("_00030012","_00030012");
define("_00030014","_00030013");
define("_00030009","_00030009");
define("_00030010","_00030010");
define("_00030007","_00030007");
define("_00100004","Web de accesibilidad");
define("_00030008","_00030008");	
define("_00030005","_00030005");	
define("_00030006","_00030006");	

//PHONE_CODES
define("_00020001","Teléfono");	
define("_00020027","Fax");	
define("_00020003","Teléfono");	
define("_00020006","Información");	

define("_INTERNETREF","Foto");	
define("_APROPDAQUI","Cerca de aquí");	
define("_COMANAR","Cómo llegar");	
define("_GMAPX","Lat");	
define("_GMAPY","Long");	
define("_MAPLABELSEARCH","Geolocalización de resultados");
define("_SHOWMAP","Ver mapa");

define("_MVIEWEDMONTH","LO MÁS VISTO");
define("_MVOTEDMONTH","ACTOS MÁS VALORADOS");
define("_CATS_AGENDA","CATEGORÍAS AGENDA");
define("_CATS_DIRECTORI","CATEGORÍAS DIRECTORIO");

define("_CATS_H_AGENDA","Agenda de actividades");
define("_CATS_H_DIRECTORI","Directorio de entidades y equipamientos");

define("_VEURE_CATS_AGENDA","Ver todos los actos de la agenda");
define("_VEURE_CATS_DIRECTORI","Ver todos los actos de la agenda");

define("_HORARIS","Horarios");
define("_PREUS","Precios");
define("_PERIOD","Periodo");
define("_DAYS", "Días");
define("_HOURS", "Horas");
define("_PRICE", "Precios");
define("_REMARKS","Observaciones"); 
define("_PERMANENT","Acto permanente"); 
define("_RECOMMENDED","LOS USUARIOS QUE HAN VISTO ESTO, TAMBIÉN HAN VISTO..."); 

define("_CLASSALL","Clasificación"); 
define("_CLASSLABEL","Oferta formativa"); 
define("_SECTION","Secciones de este equipamiento"); 
define("_RELATIONS","Otros"); 
define("_MORE","Más");
define("_NO_AV_LG","Contenido no disponible en este idioma");
define("_LIKEIT","Me gusta");

define("_P","Precios");
define("_NOPREU","No hay información");
define("_DE1A30","De 1€ a 30€");
define("_DE30A60","De 30€ a 60€");
define("_MES60","Más de 60€");

define("_D","Cuando");
define("_AVUI","Hoy");
define("_DEMA","Mañana");
define("_CAP","Este fin de semana");
define("_CAPS","Fines de semana");
define("_SETMANA","Próximos 7 dias");
define("_MES","Próximos 30 dias");

define("_DATE","Cuándo : ");//Fecha
define("_ENDDATE","al");//Del 21/1/2011 al 31/1/2011
define("_BEGINDATE","Del"); //Del 21/1/2011 al 31/1/2011
define("_PHONENUMBER","Tel.:");
define("_ID","");
define("_POS","");
define("_EQUIPMENT_ID","Equipment_id");

define("_AGEQ","Actos que se celebran aquí");
define("_NODISPONIBLE","No disponible");

define("_DROPFILTER","Eliminar filtro");
define("_YOURFILTERS","Tus filtros");
define("_FILTERS","Filtros");
define("_NUMROWS","Resultados por página");
define("_DISPLAYING","Mostrando");
define("_TO","al");
define("_RESULTS","Resultados sobre");
define("_ACTEPERMANENT","Acto Permanente");
define("_ACTDESTACADES","ACTIVIDADES DESTACADAS");
define("_TEXTE","");
define("_NOEXIST","");
define("_TP","");

define("_RELATED","Registros relacionados");
define("_APARCS","Aparcamientos");
define("_RESTAURANTS","Restaurantes");
define("_TEMA_TOTS","Todo");
define("_STATUS_ID","Estado");
define("_AG_STATUS_ID_1","Acto Aplazado");
define("_AG_STATUS_ID_2","Acto Suspendido");

 
define("_ENTITY_ID","");
define("_ENTITY_TYPE","");
define("_COORDADDRESSX","");
define("_COORDADDRESSY","");
define("_STAIR",""); 
define("_FLOOR",""); 
define("_DOOR",""); 
define("_TEMA",""); 
define("_ID_TEMA","");

define("_COMMENTS","");
define("_ACTNAME","");
define("_TICKETTYPE_CODE","");
define("_ACTTYPE","");
define("_WARNING","");
define("_INSTITUTION_ID","");
define("_VOTES","");
define("_NAMEASIA","");
define("_TITULARITAT","Titularidad");
define("_0010201001","Públicos");
define("_0010201002","Privados");
define("_0013201002","Concertados o subvencionados");

define("_N0010201001","Centro público");
define("_N0010201002","Centro privado");
define("_N0013201002","Centro concertado o subvencionado");
define("_CODE_TIT","Titularidad");
define("_CODE_INFO","Servicios");

define("_002200400","Comedor");
define("_002200410","Cocina propia");
define("_002200412","Acogida fuera del horario escolar");
define("_002200441","Actividades extraescolares/casales");

define("_ACCESSIBILITY","Accesibilidad");
define("_0010501000","Amb servei de bany per a persones amb cadira de rodes");
define("_0010501001","Accesibilidad para las personas con discapacidad");
define("_0010501002","No accessible per a persones amb disminució física");
define("_0010501003","Practicable per a persones amb disminució física (parcialment adaptat)");
define("_0010501004","Amb WC adaptat per a persones amb disminució");
define("_0010501005","Sense WC adaptat per a persones amb disminució");
define("_0010501006","Adaptat per a esportistes amb disminució");
define("_0010501007","No adaptat per a esportistes amb disminució");
define("_0010501008","Amb espai per a cadires de rodes");
define("_0010501009","Sense espai per a cadires de rodes");
define("_0010501010","Amb aparcament reservat per a persones amb disminució");
define("_0010501011","Sense aparcament reservat per a persones amb disminució");
define("_0010501012","Amb caseta vestidor adaptada per a persones amb disminució");
define("_0010501013","Amb dutxes adaptades per a persones amb disminució");
define("_0010501014","Sense dutxes adaptades per a persones amb disminució");
define("_0010501015","Parcialment adaptat per a esportistes amb disminució");
define("_0010501016","Amb vehicles adaptats per a persones amb disminució");
define("_0010501017","Adaptació de vehicles per a persones amb disminució física");
define("_0010501018","Amb visita comentada per a persones amb disminució auditiva");
define("_0010501019","Parcialment accessible per a persones amb disminució física");

?>