<?php
/**
 * Guia de Barcelona - Agenda and Directory
 *
 * This file is part of Guia Barcelona v1.0.0
 * @author Elazos Software Factory
 **/

define("_DATEFORMAT","d/m/Y");
define("_FINPAG","Copyright © ".date("Y")." <a href=\"http://www.bcn.cat\">Ajuntament de Barcelona</a> - All Rights Reserved.");
define("_SITENAME","Guia de Barcelona");
define("_SITEOWNER","Ajuntament de Barcelona");
define("_SLOGAN","Guia Barcelona");
define("_SITEDESC","Guia i Agenda d'actes i activitats, directoris d'entitats i equipaments de la ciutat de Barcelona"); 
define("_KEYWORDS","agenda, calendari, actes, acte, activitats, directori, directoris, equipament, equipaments, entitats, entitat, restaurants, associacions");
define("_CHARSET","UTF-8");
define("_IDIOMA","ca");
define("_LANGUAGE",1);
define("_HOME","Guia Bcn");
define("_PIEPAGINA","Peu de pàgina");
define("_FIND","Cerca");
define("_FOUND","Trobats");
define("_ROWS","registres");
define("_PAGS","Pàgines");   
define("_OF","de");
define("_NEXT","Següent");
define("_PREVIOUS","Anterior");

define("_NAME","Nom");
define("_TICKET","Entrada");

define("_DISTRICT","Districte");
define("_DISTRICTSTR","Districte");
define("_BARRI","Barri");
define("_BARRISTR","Barri");
define("_STREET","Adreça");
define("_STREETNUM_I","Núm");
define("_TYPE","Tipus");
define("_SECTIONNAME","Secció");
define("_ADDRESS","Adreça");
define("_POSTALCODE","Codi postal");
define("_CITY","Població");

define("_VOLIEUDIR","Volíeu dir:");
define("_SIGLA","Sigla");
define("_INSTITUTIONNAME","On:");
define("_RSS","RSS");
define("_ALPHA","Alfabèticament");
define("_POPULARITY","Popularitat");
define("_LATEST","Més recents");
define("_SORTBY","Endreçar per:");

define("_SEARCH","Resultats de la cerca:");

define("_DETALL","Detall");

define("_NOT_FOUND","No s'han trobat resultats per a la cerca");
define("_NOTFOUND","No s'ha trobat la pàgina.");

define("_AG","Agenda");
define("_EQ","Entitats i equipaments");

define("_00060001","Tiquet 60001");
define("_00060002","Gratuïta");
define("_00060003","Pagament");	
define("_00060004","Reservada");	
define("_00060005","Només grups");	
define("_00060006","Amb Invitació");	

// INTERESTINFO
define("_00100000","Informacions d'interès EQ");
define("_00100002","Adreça electrònica");
define("_00100003","Web");
define("_00100004","Web d'accessibilitat");
define("_00100005","Facebook"); 
define("_00100006","Twitter"); 
define("_00100007","YouTube"); 
define("_00100008","Instagram"); 

define("_00030001","Telèfon");
define("_00030002","Adreça electrònica");
define("_00030003","Web");
define("_00030004","Telèfon d´inscripció");
define("_00030005","Fax d'inscripcions de l'acte");
define("_00030006","Fax de venda d'entrades");
define("_00030007","Telèfon de venda d'entrades");
define("_00030008","Correu electrònic de venda d'entrades");
define("_00030009","Correu electrònic d'inscripcions");
define("_00030010","Correu electrònic de reserves");
define("_00030011","Telèfon de reserves");
define("_00030012","Web d'inscripcions");
define("_00030013","Telèfon de venda d'abonaments");
define("_00030014","Web de venda d'entrades");
define("_00030015","Vídeo");
define("_00030016","Telèfon d'informació");
define("_00030017","Facebook");
define("_00030018","Twitter");
define("_00030019","YouTube");


//PHONE_CODES
define("_00020001","Telèfon");	
define("_00020027","Fax");	
define("_00020003","Telèfon");	
define("_00020006","Informació");	

define("_INTERNETREF","Foto");	

define("_APROPDAQUI","Prop d'aquí");	
define("_COMANAR","Com s'hi va");	

define("_GMAPX","Lat");	
define("_GMAPY","Long");

define("_SHOWMAP","Mostra el mapa");
define("_MAPLABELSEARCH","Geolocalització de resultats");

define("_MVOTEDMONTH","ACTES+VALORATS");
define("_MVIEWEDMONTH","ELS+CONSULTATS");

define("_CATS_AGENDA","CATEGORIES D´AGENDA");
define("_CATS_DIRECTORI","CATEGORIES DE DIRECTORI");

define("_VEURE_CATS_AGENDA","Mostra tots els actes de l'agenda");
define("_VEURE_CATS_DIRECTORI","Mostra tots els directoris");

define("_CATS_H_AGENDA","Agenda d'activitats");
define("_CATS_H_DIRECTORI","Directori d'entitats i equipaments");

define("_HORARIS","Horaris");
define("_PREUS","Preus");
define("_PERIOD","Període");
define("_DAYS", "Dies");
define("_HOURS", "Hores");
define("_PRICE", "Preu");
define("_REMARKS","Observacions"); 
define("_PERMANENT","Acte permanent"); 
define("_RECOMMENDED","ELS USUARIS QUE HAN VIST AIXÒ, TAMBE HAN VIST..."); 

define("_CLASSALL","Classificació"); 
define("_CLASSLABEL","Aquest registre el podeu trobar a"); 
define("_SECTION","Seccions d'aquest equipament"); 
define("_RELATIONS","Altres"); 
define("_MORE","Més"); 
define("_NO_AV_LG","Contingut no disponible en aquest idioma.");
define("_LIKEIT","M'agrada");

define("_P","Preu");
define("_NOPREU","No informat");
define("_DE1A30","D'1€ a 30€");
define("_DE30A60","De 30€ a 60€");
define("_MES60","Mes de 60€");

define("_D","Quan");
define("_AVUI","Avui");
define("_DEMA","Demà");
define("_CAP","Aquest cap de setmana");
define("_CAPS","Caps de setmana");
define("_SETMANA","Propers 7 dies");
define("_MES","Propers 30 dies");

define("_DATE","Quan:");//Fecha
define("_ENDDATE","al");//Del 21/1/2011 al 31/1/2011
define("_BEGINDATE","Del"); //Del 21/1/2011 al 31/1/2011
define("_PHONENUMBER","Tel.:");
define("_ID","");
define("_POS","");
define("_EQUIPMENT_ID","Equipment_id");

define("_AGEQ","Actes que s'hi celebren");
define("_NODISPONIBLE","No disponible");


define("_DROPFILTER","Treu el filtre");
define("_YOURFILTERS","Els vostres filtres");
define("_FILTERS","Filtres");
define("_NUMROWS","resultats per pàgina");
define("_DISPLAYING","S'està mostrant del");
define("_TO","al");
define("_RESULTS","resultats sobre");
define("_ACTEPERMANENT","Acte Permanent");

define("_ACTDESTACADES","ACTIVITATS DESTACADES");
define("_RECOM_ID","id");
define("_IMATGECOS","Imatge cos"); 
define("_IMATGE","Imatge"); 
define("_TITOL","Títol"); 
define("_RESUM","Resum"); 
define("_URLVIDEO","Video"); 
define("_ENTITY_ID","entity_id");
define("_TEXTE","");
define("_NOEXIST","");
define("_TP","");

define("_RELATED","Registres relacionats");
define("_APARCS","Aparcaments");
define("_RESTAURANTS","Restaurants");
define("_TEMA_TOTS","Tot");
define("_STATUS_ID","Estat");
define("_AG_STATUS_ID_1","Acte Ajornat");
define("_AG_STATUS_ID_2","Acte Suspès");


define("_ENTITY_TYPE","");
define("_COORDADDRESSX","");
define("_COORDADDRESSY","");
define("_STAIR",""); 
define("_FLOOR",""); 
define("_DOOR",""); 
define("_TEMA",""); 
define("_ID_TEMA","");

define("_COMMENTS","");
define("_ACTNAME","");
define("_TICKETTYPE_CODE","");
define("_ACTTYPE","");
define("_WARNING","");
define("_INSTITUTION_ID","");
define("_VOTES","");
define("_NAMEASIA","");
define("_TITULARITAT","Titularitat");
define("_0010201001","Públics");
define("_0010201002","Privats");
define("_0013201002","Concertats");

define("_N0010201001","Centre públic");
define("_N0010201002","Centre privat");
define("_N0013201002","Centre concertat");
define("_CODE_TIT","Titularitat");
define("_CODE_INFO","Serveis");

define("_002200400","Menjador");
define("_002200410","Cuina pròpia");
define("_002200412","Serveis d'acollida fora d'horari escolar");
define("_002200441","Activitats extraescolars");

define("_HOMEBCNTITOL","Agenda");
define("_HOMEBCNTOTS","Tots els actes a bcn.cat");
define("_HOMEBCNTITOL2","<span>Guia BCN</span> et recomana");
define("_HOMEBCNTOTS2","Vés a la Guia BCN");

define("_ACCESSIBILITY","Accessibilitat");
define("_0010501000","Amb servei de bany per a persones amb cadira de rodes");
define("_0010501001","Accessibilitat per a les persones amb discapacitat");
define("_0010501002","No accessible per a persones amb disminució física");
define("_0010501003","Practicable per a persones amb disminució física (parcialment adaptat)");
define("_0010501004","Amb WC adaptat per a persones amb disminució");
define("_0010501005","Sense WC adaptat per a persones amb disminució");
define("_0010501006","Adaptat per a esportistes amb disminució");
define("_0010501007","No adaptat per a esportistes amb disminució");
define("_0010501008","Amb espai per a cadires de rodes");
define("_0010501009","Sense espai per a cadires de rodes");
define("_0010501010","Amb aparcament reservat per a persones amb disminució");
define("_0010501011","Sense aparcament reservat per a persones amb disminució");
define("_0010501012","Amb caseta vestidor adaptada per a persones amb disminució");
define("_0010501013","Amb dutxes adaptades per a persones amb disminució");
define("_0010501014","Sense dutxes adaptades per a persones amb disminució");
define("_0010501015","Parcialment adaptat per a esportistes amb disminució");
define("_0010501016","Amb vehicles adaptats per a persones amb disminució");
define("_0010501017","Adaptació de vehicles per a persones amb disminució física");
define("_0010501018","Amb visita comentada per a persones amb disminució auditiva");
define("_0010501019","Parcialment accessible per a persones amb disminució física");

define("_CODE_URL","Web");
define("_STATUS","Estat");
define("_ATENCIO_EQ","Atenció");
define("_CODE_COMARCA","Comarca");

define("_ESMENA_AG","Si voleu fer una esmena sobre aquesta activitat feu-nos-la arribar");


?>